# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 872b8b3e23baf9bb118f6ca67981209a9c9876651003b36669bfff26722bf3eeb4600231c41a6962834843b981256eb8aa44aca93d5d7864294fe7eae5b9342f

test:
  secret_key_base: 516b903396b41e03db707929ea71d6677b7b36b116b20cd662e0668e316edf1af2b6d7e048588ee0a30377408c8cb71c32d49df02063e1183558911ae08c7ae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
